var theDaily = [
  /*
  "Be yourself; everyone else is already taken",
  "You've gotta dance like there's nobody watching, Love like you'll never be hurt, Sing like there's nobody listening, And live like it's heaven on earth.",
  "Be the change that you wish to see in the world",
  "No one can make you feel inferior without your consent",
  "Live as if you were to die tomorrow. Learn as if you were to live forever",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that",
  "Without music, life would be a mistake",
  "We accept the love we think we deserve",
  "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring",
  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle",
  "We are all in the gutter, but some of us are looking at the stars",
  "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present",
  "I have not failed. I've just found 10,000 ways that won't work",
  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference",
  "I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who'll decide where to go..",
  "It is never too late to be what you might have been",
  "This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about",
  "There is no greater agony than bearing an untold story inside you",
  "Everything you can imagine is real",
  "You can never get a cup of tea large enough or a book long enough to suit me",
  "To the well-organized mind, death is but the next great adventure",
  "Life isn't about finding yourself. Life is about creating yourself",
  "Do what you can, with what you have, where you are",
  "Listen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be",
  "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us",
  "Success is not final, failure is not fatal: it is the courage to continue that counts",
  "So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be",
  "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one",
  "And, when you want something, all the universe conspires in helping you to achieve it",
  "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, 'Who am I to be brilliant, gorgeous, talented, fabulous?' Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It's not just in some of us; it's in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others",
  "It’s no use going back to yesterday, because I was a different person then",
  "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain",
  "A person's a person, no matter how small",
  "It's the possibility of having a dream come true that makes life interesting",
  "He’s not perfect. You aren’t either, and the two of you will never be perfect. But if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can. He isn’t going to quote poetry, he’s not thinking about you every moment, but he will give you a part of him that he knows you could break. Don’t hurt him, don’t change him, and don’t expect for more than he can give. Don’t analyze. Smile when he makes you happy, yell when he makes you mad, and miss him when he’s not there. Love hard when there is love to be had. Because perfect guys don’t exist, but there’s always one guy that is perfect for you",
  "When we honestly ask ourselves which person in our lives mean the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand. The friend who can be silent with us in a moment of despair or confusion, who can stay with us in an hour of grief and bereavement, who can tolerate not knowing, not curing, not healing and face with us the reality of our powerlessness, that is a friend who cares",
  "You can't live your life for other people. You've got to do what's right for you, even if it hurts some people you love",
  "Well-behaved women seldom make history",
  "When I despair, I remember that all through history the way of truth and love have always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it--always",
  "Nothing is impossible, the word itself says 'I'm possible'",
  "So we beat on, boats against the current, borne back ceaselessly into the past",
  "I can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time",
  "Do what you feel in your heart to be right – for you’ll be criticized anyway",
  "[...]the only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn like fabulous yellow roman candles exploding like spiders across the stars and in the middle you see the blue centerlight pop and everybody goes “Awww",
  "Happiness is not something ready made. It comes from your own actions",
  "Peace begins with a smile.",
  "Imagining the future is a kind of nostalgia. (...) You spend your whole life stuck in the labyrinth, thinking about how you'll escape it one day, and how awesome it will be, and imagining that future keeps you going, but you never do it. You just use the future to escape the present",
  "Do not read, as children do, to amuse yourself, or like the ambitious, for the purpose of instruction. No, read in order to live",
  "Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has",
  "For attractive lips, speak words of kind",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us",
  "Promise You",
  "Friendship is unnecessary, like philosophy, like art.... It has no survival value; rather it is one of those things which give value to survival",
  "Whatever you are, be a good one",
  "Two wrongs don't make a right, but they make a good excuse",
  "I hope she'll be a fool -- that's the best thing a girl can be in this world, a beautiful little fool",
  "First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you",
  "May you live every day of your life",
  "I believe that imagination is stronger than knowledge. That myth is more potent than history. That dreams are more powerful than facts. That hope always triumphs over experience. That laughter is the only cure for grief. And I believe that love is stronger than death",
  "You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes",
  "Isn't it nice to think that tomorrow is a new day with no mistakes in it yet",
  "If my life is going to mean anything, I have to live it myself",
  "Who controls the past controls the future. Who controls the present controls the past",
  "You can talk with someone for years, everyday, and still, it won't mean as much as what you can have when you sit in front of someone, not saying a word, yet you feel that person with your heart, you feel like you have known the person for forever.... connections are made with the heart, not the tongue",
  "Hope is the thing with feat",
  "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life",
  "Always do what you are afraid to do",
  "Our lives begin to end the day we become silent about things that matter",
  "There is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more. He who has felt the deepest grief is best able to experience supreme happiness. We must have felt what it is to die, Morrel, that we may appreciate the enjoyments of l",
  "In the end, we will remember not the words of our enemies, but the silence of our friends",
  "Pain is inevitable. Suffering is optional",
  "Do not let your fire go out, spark by irreplaceable spark in the hopeless swamps of the not-quite, the not-yet, and the not-at-all. Do not let the hero in your soul perish in lonely frustration for the life you deserved and have never been able to reach. The world you desire can be won. It exists.. it is real.. it is possible.. it's yours",
  "It is so hard to leave—until you leave. And then it is the easiest goddamned thing in the world",
  "Talent hits a target no one else can hit. Genius hits a target no one else can see",
  "If you're reading th",
  "And once the storm is over, you won’t remember how you made it through, how you managed to survive. You won’t even be sure, whether the storm is really over. But one thing is certain. When you come out of the storm, you won’t be the same person who walked in. That’s what this storm’s all about",
  "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
  "Waiting is painful. Forgetting is painful. But not knowing which to do is the worst kind of suffering",
  "Fantasy is hardly an escape from reality. It's a way of understanding it",
  "I can be changed by what happens to me. But I refuse to be reduced b",
  "Do not go where the path may lead, go instead where there is no path and leave a trail",
  "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater",
  "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward",
  "Never let your sense of morals prevent you from doing what is right",
  "I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass",
  "When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth",
  "Hell is empty and all the devils are here",
  "Turn your wounds into wisdom",
  "No one can make you feel inferior without your consent",
  "It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it",
  "The fool doth think he is wise, but the wise man knows himself to be a fool",
  "Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect)",
  "When someone loves you, the way they talk about you is different. You feel safe and comfortable",
  "Knowing yourself is the beginning of all wisdom",
  "The only true wisdom is in knowing you know nothing",
  "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom",
  "Count your age by friends, not years. Count your life by smiles, not tears",
  "Hold fast to dr",
  "In a good bookroom you feel in some mysterious way that you are absorbing the wisdom contained in all the books through your skin, without even opening them",
  "May you live every day of your life",
  "Never laugh at live dragons",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it",
  "The secret of life, though, is to fall seven times and to get up eight times",
  "There is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more. He who has felt the deepest grief is best able to experience supreme happiness. We must have felt what it is to die, Morrel, that we may appreciate the enjoyments of l",
  "If you're reading th",
  "The best index to a person's character is how he treats people who can't do him any good, and how he treats people who can't fight back",
  "Any fool can know. The point is to understand",
  "Think before you speak. Read before you think",
  "Never let your sense of morals prevent you from doing what is right",
  "Turn your wounds into wisdom",
  "The unexamined life is not worth living",
  "The simple things are also the most extraordinary things, and only the wise can see them",
  "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest",
  "There are three things all wise men fear: the sea in storm, a night with no moon, and the anger of a gentle man",
  "Angry people are not always wise",
  "It's a dangerous business, Frodo, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to",
  "You do not write your life with words...You write it with actions. What you think is not important. It is only important what",
  "Let no man pull you so low as to hate him",
  "It is amazing how complete is the delusion that beauty is goodness",
  "God will not look you over for medals, degrees or diplomas but for scars",
  "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones",
  "Knowing others is intellig",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself",
  "The man of knowledge must be able not only to love his enemies but also to hate his friends",
  "You will do foolish things, but do them with enthusiasm",
  "The only way to get through life is to laugh your way through it. You either have to laugh or cry. I prefer to laugh. Crying gives me a headache",
  "I'm not young enough to know everything",
  "Trees are poems the earth writes upon the sky, We fell them down and turn them into p",
  "It is not that I'm so smart. But I stay with the questions much longer",
  "The measure of intelligence is the ability to change",
  "Failure is the condiment that gives success its flavor",
  "Don't Gain The World & Lose Your Soul, Wisdom Is Better Than Silver Or Gold",
  "Knowledge speaks, but wisdom listen",
  "The past has no power over the present moment",
  "We must be willing to let go of the life we planned so as to have the life that is waiting for us",
  "You yourself, as much as anybody in the entire universe, deserve your love and affectio",
  "Don't waste your time with explanations: people only hear what they want to hear",
  "I am looking for friends. What does that mean -- t",
  "The mind once enlightened cannot again become dark",
  "Sell your cleverness and buy bewilderment",
  "Even strength must bow to wisdom sometimes",
  "We can know only that we know nothing. And that is the highest degree of human wisdom",
  "There are moments when troubles enter our lives and we can do nothing to avoid ",
  "I’m not in this world to live up to your expectations and you’re not in this world to live up to mine",
  "Music is ... A higher revelation than all Wisdom & Philosoph",
  "The desire to reach for the stars is ambitious. The desire to reach hearts is wise",
  "He who knows all the answers has not been asked all the questions",
  "Do you not see how necessary a world of pains and troubles is to school an intelligence and make it a soul",
  "We learn from failure, not from success",
  "The more I read, the more I acquire, the more certain I am that I know nothing",
  "Pain is a pesky part of being human, I've learned it feels like a stab wound to the heart, something I wish we could all do without, in our lives here. Pain is a sudden hurt that can't be escaped. But then I have also learned that because of pain, I can feel the beauty, tenderness, and freedom of healing. Pain feels like a fast stab wound to the heart. But then healing feels like the wind against your face when you are spreading your wings and flying through the air! We may not have wings growing out of our backs, but healing is the closest thing that will give us that wind against our faces",
  "Perhaps the rare and simple pleasure of being seen for what one is compensates for the misery of being it",
  "Anybody can look at a pretty girl and see a pretty girl. An artist can look at a pretty girl and see the old woman she will become. A better artist can look at an old woman and see the pretty girl that she used to be. But a great artist-a master-and that is what Auguste Rodin was-can look at an old woman, protray her exactly as she is...and force the viewer to see the pretty girl she used to be...and more than that, he can make anyone with the sensitivity of an armadillo, or even you, see that this lovely young girl is still alive, not old and ugly at all, but simply prisoned inside her ruined body. He can make you feel the quiet, endless tragedy that there was never a girl born who ever grew older than eighteen in her heart...no matter what the merciless hours have done to her. Look at her, Ben. Growing old doesn't matter to you and me; we were never meant to be admired-but it does to them",
  "Never, never, never give in",
  "The older I grow, the more I distrust the familiar doctrine that age brings wisdom",
  "We shall not cease from explor",
  "We live in an age when unnecessary things are our only necessities",
  "Follow your heart, listen to your inner voice, stop caring about what others think",
  "In youth, it was a way I",
  "All knowledge hurts",
  "There comes a point when you either embrace who and what you are, or condemn yourself to be miserable all your days. Other people will try to make you miserable; don't help them by doing the job yourself",
  "Authority without wisdom is like a heavy axe without an edge, fitter to bruise than polish",
  "I think I've discovered the secret of life -- you just hang around until you get used to it",
  "You can search throughout the entire universe for someone who is more deserving of your love and affection than you are yourself, and that person is not to be found anywhere. You, yourself, as much as anybody in the entire universe, deserve your love and affection",
  "Death is no more than passing from one room into another. But there's a difference for me, you know. Because in that other room I shall be able to see",
  "That's what real love amounts to - letting a person be what he really is. Most people love you for who you pretend to be. To keep their love, you keep pretending - performing. You get to love your pretence. It's true, we're locked in an image, an act - and the sad thing is, people get so used to their image, they grow attached to their masks. They love their chains. They forget all about who they really are. And if you try to remind them, they hate you for it, they feel like you're trying to steal their most precious possession",
  "Wonder is the beginning of wisdom",
  "Wisdom cannot be imparted. Wisdom that a wise man attempts to impart always sounds like foolishness to someone else ... Knowledge can be communicated, but not wisdom. One can find it, live it, do wonders through it, but one cannot communicate and teach it",
  "Sometimes one likes foolish people for their folly, better than wise people for their wisdom",
  "Common sense in an uncommon degree is what the world calls wisdom",
  "Learn to light a candle in the darkest moments of someone’s life. Be the light that helps others see; it is what gives life its deepest significance",
  "Mockingbirds don’t do one thing but make music for us to enjoy. They don’t eat up people’s gardens, don’t nest in corncribs, they don’t do one thing but sing their hearts out for us. That’s why it’s a sin to kill a mockingbird",
  "Nowadays most people die of a sort of creeping common sense, and discover when it is too late that the only things one never regrets are one's mistakes",
  "Risks must be taken because the greatest hazard in life is to risk nothing",
  "Life would be tragic if it weren't funny",
  "Half of seeming clever is keeping your mouth shut at the right times",
  "Never complain, never explain. Resist the temptation to defend yourself or make excuses",
  "It is one thing to be clever and another to be wise",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe",
  "So many books, so little time",
  "You only live once, but if you do it right, once is enough",
  "Insanity is doing the same thing, over and over again, but expecting different results",
  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid",
  "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read",
  "A day without sunshine is like, you know, night",
  "Never put off till tomorrow what may be done day after tomorrow just as well",
  "I love deadlines. I love the whooshing noise they make as they go by",
  "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car",
  "Women and cats will do as they please, and men and dogs should relax and get used to the idea",
  "All you need is love. But a little chocolate now and then doesn't hurt",
  "Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye",
  "I'm not afraid of death; I just don't want to be there when it happens",
  "Whenever I feel the need to exercise, I lie down until it goes away",
  "Saying 'I notice you're a nerd' is like saying, 'Hey, I notice that you'd rather be intelligent than be stupid, that you'd rather be thoughtful than be vapid, that you believe that there are things that matter more than the arrest record of Lindsay Lohan. Why is that?' In fact, it seems to me that most contemporary insults are pretty lame. Even 'lame' is kind of lame. Saying 'You're lame' is like saying 'You walk with a limp.' Yeah, whatever, so does 50 Cent, and he's done all right for himself",
  "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book",
  "Some people never go crazy. What truly horrible lives they must lead",
  "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it",
  "Reality continues to ruin my life",
  "The reason I talk to myself is because I’m the only one whose answers I accept",
  "Go to heaven for the climate and hell for the company",
  "I am free of all prejudice. I hate everyone equally.",
  "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment",
  "It’s no use going back to yesterday, because I was a different person then",
  "Be nice to nerds. You may end up working for them. We all could",
  "Be careful about reading health books. Some fine day you'll die of a misprint",
  "Have you ever noticed how ‘What the hell’ is always the right decision to make",
  "Creativity is knowing how to hide your source",
  "Fate is like a strange, unpopular restaurant filled with odd little waiters who bring you things you never asked for and don't always like",
  "The statistics on sanity are that one out of every four people is suffering from a mental illness. Look at your 3 best friends. If they're ok, then it's you",
  "Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life",
  "All God does is watch us and kill us when we get boring. We must never, ever be boring",
  "This life’s hard, but it’s harder if you’re stupid",
  "I refuse to answer that question on the grounds that I don't know the answe",
  "He can run faster than Severus Snape confronted with shampoo",
  "Mr. Moony presents his compliments to Professor Snape, and begs him to keep his abnormally large nose out of other people's busi",
  "Is it true that you shouted at Professor Umbri",
  "Never memorize something that you can look up",
  "When you're in jail, a good friend will be trying to bail you out. A best friend will be in the cell next to you saying, 'Damn, that was fun'",
  "Some humans would do anything to see if it was possible to do it. If you put a large switch in some cave somewhere, with a sign on it saying 'End-of-the-World Switch. PLEASE DO NOT TOUCH', the paint wouldn't even have time to dry",
  "There's a fine line between genius and insanity. I have erased this line",
  "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity",
  "Two wrongs don't make a right, but they make a good excuse",
  "If the world were merely seductive, that would be easy. If it were merely challenging, that would be no problem. But I arise in the morning torn between a desire to improve the world and a desire to enjoy the world. This makes it hard to plan the day",
  "Reader, suppose you were an idiot. And suppose you were a member of Congress. But I repeat myself",
  "I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal",
  "Do you remember back at the hotel when you promised that if we lived, you’d get dressed up in a nurse’s outfit and give me a sponge bath?" asked ",
  "The planet is fine. The people are fucked",
  "I like work: it fascinates me. I can sit and look at it for hours",
  "If a cluttered desk is a sign of a cluttered mind, of what, then, is an empty desk a sign",
  "When his life was ruined, his family killed, his farm destroyed, Job knelt down on the ground and yelled up to the heavens, "Why god? Why me?" and the thundering voice of God answered, There's just something about you that pisses me off",
  "There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplica",
  "There are two motives for reading a book; one, that you enjoy it; the other, that you can boast about it",
  "I did not attend his funeral, but I sent a nice letter saying I approved of it",
  "Where is human nature so weak as in the bookstore",
  "If at first you don't succeed, try, try again. Then quit. No use being a damn fool about it",
  "It is hard enough to remember my opinions, without also remembering my reasons for them",
  "I generally avoid temptation unless I can't resist it",
  "So please, oh please, we beg, we ",
  "Happiness is a warm puppy",
  "I don't know the question, but sex is definitely the answer",
  "Never let your sense of morals prevent you from doing what is right",
  "I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass",
  "I was gratified to be able to answer promptly, and I did. I said I didn’t know",
  "Fantasy is a necessary ingredient in living, it's a way of looking at life through the wrong end of a telescope",
  "Percy wouldn't notice a joke if it danced naked in front of him wearing one of Dobby's hats",
  "I have great faith in fools - self-confidence my friends will call it",
  "Religion has actually convinced people that there's an invisible man living in the sky who watches everything you do, every minute of every day. And the invisible man has a special list of ten things he does not want you to do. And if you do any of these ten things, he has a special place, full of fire and smoke and burning and torture and anguish, where he will send you to live and suffer and burn and choke and scream and cry forever and ever 'til the end of ",
  "Time flies like an arrow; fruit flies like a banana",
  "It is said that your life flashes before your eyes just before you die. That is true, it's called Life",
  "I think God, in creating man, somewhat overestimated his ability",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe",
  "Be the change that you wish to see in the world",
  "Without music, life would be a mistake",
  "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference",
  "Go to heaven for the climate and hell for the company",
  "A day without laughter is a day wasted",
  "Have you ever noticed how ‘What the hell’ is always the right decision to make",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world",
  "Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has",
  "You talk when you cease to be at peace with your thoughts",
  "May you live every day of your life",
  "We have to dare to be ourselves, however frightening or strange that self may prove to be",
  "Man is the only creature who refuses to be what he is",
  "If a cluttered desk is a sign of a cluttered mind, of what, then, is an empty desk a sign",
  "One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don't throw it away",
  "It is hard enough to remember my opinions, without also remembering my reasons for them",
  "There is nothing either good or bad, but thinking makes it so",
  "Never let your sense of morals prevent you from doing what is right",
  "A human being is a part of the whole called by us universe, a part limited in time and space. He experiences himself, his thoughts and feeling as something separated from the rest, a kind of optical delusion of his consciousness. This delusion is a kind of prison for us, restricting us to our personal desires and to affection for a few persons nearest to us. Our task must be to free ourselves from this prison by widening our circle of compassion to embrace all living creatures and the whole of nature in its beauty",
  "Wise men speak because they have something to say; fools because they have to say something",
  "You do not write your life with words...You write it with actions. What you think is not important. It is only important what",
  "Trust yourself. You know more than you think you do",
  "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try",
  "Simplicity, patience, compas",
  "Without deviation from the norm, progress is not possible",
  "There may be times when we are powerless to prevent injustice, but there must never be a time when we fail to protest",
  "A woman has to live her life, or live to repent not having lived it",
  "Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric",
  "The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science",
  "Fantasy is escapist, and that is its glory. If a soldier is imprisioned by the enemy, don't we consider it his duty to escape?. . .If we value the freedom of mind and soul, if we're partisans of liberty, then it's our plain duty to escape, and to take as many people with us as we can",
  "We are all atheists about most of the gods that humanity has ever believed in. Some of us just go one god further",
  "You're not to be so blind with patriotism that you can't face reality. Wrong is wrong, no matter who does it or says it",
  "I was within and without, simultaneously enchanted and repelled by the inexhaustible variety of life",
  "If you ever find yourself in the wrong story, leave",
  "Maybe everyone can live beyond what they're capable of",
  "Let's think the unthinkable, let's do the undoable. Let us prepare to grapple with the ineffable itself, and see if we may not eff it after all",
  "Time is an illusion. Lunchtime doubly so",
  "The past has no power over the present moment",
  "When we are tired, we are attacked by ideas we conquered long ago",
  "A truth that's told with bad i",
  "The reasonable man adapts himself to the world: the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man",
  "I cannot teach anybody anything. I can only make them thin",
  "Those who know do not speak. Those who speak do not know",
  "We are addicted to our thoughts. We cannot change anything if we cannot change our thinking",
  "You only live t",
  "Heard melodies are sweet, but those unheard, are sweete",
  "A paranoid is someone who knows a little of what's going on.",
  "The price good men pay for indifference to public affairs is to be ruled by evil men",
  "Music is ... A higher revelation than all Wisdom & Philosoph",
  "The easy confidence with which I know another man's religion is folly teaches me to suspect that my own is also",
  "It is easy in the world to live after the world's opinion; it is easy in solitude to live after our own; but the great man is he who in the midst of the crowd keeps with perfect sweetness the independence of solitude",
  "A concept is a brick. It can be used to build a courthouse of reason. Or it can be thrown through the window",
  "If you win, you need not have to explain...If you lose, you should not be there to explain",
  "Like all magnificent things, it's very simple",
  "I must say a word about fear. It is life's only true opponent. Only fear can defeat life. It is a clever, treacherous adversary, how well I know. It has no decency, respects no law or convention, shows no mercy. It goes for your weakest spot, which it finds with unnerving ease. It begins in your mind, always ... so you must fight hard to express it. You must fight hard to shine the light of words upon it. Because if you don't, if your fear becomes a wordless darkness that you avoid, perhaps even manage to forget, you open yourself to further attacks of fear because you never truly fought the opponent who defeated you",
  "Morality is simply the attitude we adopt towards people we personally dislike",
  "Science is not only compatible with spirituality; it is a profound source of spirituality",
  "An intellectual? Yes. And never deny it. An intellectual is someone whose mind watches itself. I like this, because I am happy to be both halves, the watcher and the watched. \"Can they be brought together?\" This is a practical question. We must get down to it. \"I despise intelligence\" really means: \"I cannot bear my doubts\"",
  "For me, I am driven by two main philosophies: know more today about the world than I knew yesterday and lessen the suffering of others. You'd be surprised how far that gets you",
  "It is not true that people stop pursuing dreams because they grow old, they grow old because they stop pursuing dreams",
  "Life is really simple, but we insist on making it complicated",
  "Grown-ups never understand anything by themselves, and it is tiresome for children to be always and forever explaining things to the",
  "Do not train a child to learn by force or harshness; but direct them to it by what amuses their minds, so that you may be better able to discover with accuracy the peculiar bent of the genius of each",
  "Tiger got to hunt, bird got to",
  "A serious and good philosophical work could be written consisting entirely of jokes",
  "Let children read whatever they want and then talk about it with them. If parents and kids can talk together, we won't have as much censorship because we won't have as much fear",
  "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light",
  "Sometimes I lie awake at night and I ask, \"Is life a multiple choice test or is it a true or false test?\" ...Then a voice comes to me out of the dark and says, "We hate to tell you this but life is a thousand word essay",
  "Well, I must endure the presence of a few caterpillars if I wish to become acquainted with the butterflies",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing",
  "Is it possible, in the final analysis, for one human being to achieve perfect understanding of ano",
  "Nothing was ever in tune. People just blindly grabbed at whatever there was: communism, health foods, zen, surfing, ballet, hypnotism, group encounters, orgies, biking, herbs, Catholicism, weight-lifting, travel, withdrawal, vegetarianism, India, painting, writing, sculpting, composing, conducting, backpacking, yoga, copulating, gambling, drinking, hanging around, frozen yogurt, Beethoven, Back, Buddha, Christ, TM, H, carrot juice, suicide, handmade suits, jet travel, New York City, and then it all evaporated and fell apart. People had to find things to do while waiting to die. I guess it was nice to have a choice",
  "Be like water making its way through cracks. Do not be assertive, but adjust to the object, and you shall find a way around or through it. If nothing within you stays rigid, outward things will disclose themsel",
  "I would believe only in a God that knows how to dance",
  "Be kind, for everyone you meet is fighting a hard battle",
  "It's not all bad. Heightened self-consciousness, apartness, an inability to join in, physical shame and self-loathing—they are not all bad. Those devils have been my angels. Without them I would never have disappeared into language, literature, the mind, laughter and all the mad intensities that made and unmade me",
  "If you're going to kick authority in the teeth, you might as well use two feet",
  "You didn't kill him. He would have killed you, but you didn't kill ",
  "The true man wants two things: danger and play. For that reason he wants woman, as the most dangerous plaything",
  "The day the power of love overrules the love of power, the world will know peace",
  "Today a young man on acid realized that all matter is merely energy condensed to a slow vibration, that we are all one consciousness experiencing itself subjectively, there is no such thing as death, life is only a dream, and we are the imagination of ourselves. Heres Tom with the Weather",
  "The first duty of a man is to think for himsel",
  "The smallest minority on earth is the individual. Those who deny individual rights cannot claim to be defenders of minorities",
  "It is an ironic habit of human beings to run faster when they have lost their way",
  "I don’t know what’s worse: to not know what you are and be happy, or to become what you’ve always wanted to be, and feel alone",
  "Time is a game played beautifully by children",
  "Expect everything, I always say, and the unexpected never happens",
  "I shall look at you out of the corner of my eye, and you will say nothing. Words are the source of misunderstandings",
  "I started my life with a single absolute: that the world was mine to shape in the image of my highest values and never to be given up to a lesser standard, no matter how long or hard the struggle",
  "The legitimate powers of government extend to such acts only as are injurious to others. It does me no injury for my neighbor to say there are twenty gods or no god. It neither picks my pocket nor breaks my leg",
  "Don’t sacrifice yourself too much, because if you sacrifice too much there’s nothing else you can give and nobody will care for you",
"He that breaks a thing to find out what it is has left the path of wisdom",
"Your conscience is the measure of the honesty of your selfish",
"Wisdom is not a product of schooling but of the lifelong attempt to acquire it",
"A fit, healthy body—that is the best fashion statemen",
"We must live together as brothers or perish together as fools",
"As if you could kill time without injuring eternity",
"The lotus is the most beautiful flower, whose petals open one by one. But it will only grow in the mud. In order to grow and gain wisdom, first you must have the mud --- the obstacles of life and its suffering. ... The mud speaks of the common ground that humans share, no matter what our stations in life. ... Whether we have it all or we have nothing, we are all faced with the same obstacles: sadness, loss, illness, dying and death. If we are to strive as human beings to gain more wisdom, more kindness and more compassion, we must have the intention to grow as a lotus and open each petal one by one.",
"People who know little are usually great talkers, while men who know much say little",
"It's not what you say out of your mouth that determines your life, it's what you whisper to yourself that has the most power",
"It takes a very long time to become young",
"I AM IGNORANT of absolute truth. But I am humble before my ignorance and therein lies my honor and my reward",
"The journey is what brings us happiness not the destination",
"There is more in you of good than you know, child of the kindly West. Some courage and some wisdom, blended in measure. If more of us valued food and cheer and song above hoarded gold, it would be a merrier world",
"I felt like an animal, and animals don’t know sin, do they",
"Books loved anyone who opened them, they gave you secruity and friendship and didn't ask for anything in return; they never went away, never, not even when you treated them badly.",
"It does not matter how long you are spending on the earth, how much money you have gathered or how much attention you have received. It is the amount of positive vibration you have radiated in life that matters",
"People know what they do; frequently they know why they do what they do; but what they don't know is what what they do does",
"Guard well your thoughts when alone and your words when accompanied",
"Recognizing power in another does not diminish your own",
"A wise man gets more use from his enemies than a fool from his friends",
"The stupid neither forgive nor forget; the naive forgive and forget; the wise forgive but do not forget",
"Hide not your talents, they for use were ",
"A smart person knows how to talk. A wise person knows when to be silent",
"The art of being wise is knowing what to overlook",
"Into the darkness they go, the wise and the lovely.",
"But magic is neither good nor evil. It is a tool, like a knife. Is a knife evil? Only if the wielder is evil",
"No man is poor who has a Godly mother",
"If opportunity doesn't knock, build a doo",
"There are no ordinary moments",
"Sometimes it's not enough to know what things mean, sometimes you have to know what things don't mean",
"wisdom comes to us when it can no longer do any good",
"No, that is the great fallacy: the wisdom of old men. They do not grow wise. They grow careful",
"It's now very common to hear people say, 'I'm rather offended by that.' As if that gives them certain rights. It's actually nothing more... than a whine. 'I find that offensive.' It has no meaning; it has no purpose; it has no reason to be respected as a phrase. 'I am offended by that.' Well, so fucking w",
"Take it moment by moment, and you will find that we are all, as I’ve said before, bugs in amber",
"A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise",
"Wisely and slow; they stumble that run fast",
"Knowledge comes, but wisdom lingers",
"V-Day…if you need this one day in a year to show everyone else you truly care for “your loved one” I think it’s quite stupid. I hate this commercialism. It’s all artificial, and has nothing to do with real love",
"But what if I make a mistake?' Will a",
"You will not be punished for your anger; you will be punished by your anger",
"You cannot control what happens to you, but you can control your atti",
"Transformation is my favorite game and in my experience, anger and frustration are the result of you not being authentic somewhere in your life or with someone in your life. Being fake about anything creates a block inside of you. Life can’t work for you if you don’t show up as you",
"If you have a dream, don’t just sit there. Gather courage to believe that you can succeed and leave no stone unturned to make it a reality",
"I think it's impossible to really understand somebody, what they want, what they believe, and not love them the way they love themselves",
"Never respond to an angry person with a fiery comeback, even if he deserves it...Don't allow his anger to become your anger",
"For everything in this journey of life we are on, there is a right wing and a left wing: for the wing of love there is anger; for the wing of destiny there is fear; for the wing of pain there is healing; for the wing of hurt there is forgiveness; for the wing of pride there is humility; for the wing of giving there is taking; for the wing of tears there is joy; for the wing of rejection there is acceptance; for the wing of judgment there is grace; for the wing of honor there is shame; for the wing of letting go there is the wing of keeping. We can only fly with two wings and two wings can only stay in the air if there is a balance. Two beautiful wings is perfection. There is a generation of people who idealize perfection as the existence of only one of these wings every time. But I see that a bird with one wing is imperfect. An angel with one wing is imperfect. A butterfly with one wing is dead. So this generation of people strive to always cut off the other wing in the hopes of embodying their ideal of perfection, and in doing so, have created a crippled race",
"I used to think the worst thing in life is to end up all alone. It's not. The worst thing in life is to end up with people who make you feel all alone",
"It is strange how often a heart must be br",
"Simple can be harder than complex: You have to work hard to get your thinking clean to make it simple. But it’s worth it in the end because once you get there, you can move mountains",
"We should forgive our enemies, but not before they are hange",
"Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure, than to take rank with those poor spirits who neither enjoy much nor suffer much, because they live in the gray twilight that knows neither victory nor defeat",
"Prediction is very difficult, especially about the future",
"In fact, the mere act of opening the box will determine the state o",
"Madame, all stories, if continued far enough, end in death, and he is no true-story teller who would keep that from you",
"Don't go looking for boys in the",
*/
"There is a wisdom of the head, and... there is a wisdom of the heart",
"Where wisdom reigns, there is no conflict between thinking and feeling",
"You cannot teach a man anything, you can only help him find it within himself",
"In order to rise from its own ashes, a Phoenix first must burn",
          ];


//today's date:
var dayCount = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
  var today = new Date();
    var mn = today.getMonth();
    var dn = today.getDate();
    var dayOfYear = dayCount[mn] + dn;

function GimmeQuote() {
  alert('test')
document.getElementById('quote').innerHTML = theDaily[1];
}
//theDaily[dayofYear-1];
